# Datasets Configuration
dataset:
  train:
    path: "data/split/train.csv"
  val:
    path: "data/split/val.csv"
  test:
    path: "data/split/test.csv"  
  train_feature: ['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount']
  target: 'Class'     

# Data Preprocessing Configuration
preprocessing:
  scaler_type: robust

balancing:
  do_balance: True
  method: under # over - smote - under
  sampling_strategy: 0.05


# Additional Configurations
random_seed: 16

